# Generated by Django 5.0.3 on 2024-04-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
