# Generated by Django 5.0.3 on 2024-03-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_data',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
